version: '3'

services: 
  api:
    container_name: ${PROJECT}.api
    image: ${PROJECT}.api:dev-${TAG}
    restart: ${SERVICES_RESTART_TYPE}
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
    environment: 
      - USE_DOCKER=true
    env_file: 
      - .env
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8083:3000
