openapi: "3.0.2"

info:
  title: WatermelonDB Sync API Docs
  description: WatermelonDB Sync API documentation.
  version: "1.0"

servers:
  - url: http://localhost:3000/v1

tags:
  - name: auth
    description: Auth resources

paths:



